version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: translation-service
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - translation-network
    depends_on:
      - db
      - redis
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=translation_service
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  nginx:
    image: nginx:alpine
    container_name: translation-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - translation-network

  db:
    image: mysql:8.0
    container_name: translation-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: translation_service
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - translation-network

  redis:
    image: redis:alpine
    container_name: translation-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - translation-network

networks:
  translation-network:
    driver: bridge

volumes:
  dbdata:
    driver: local